//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public long book_id { get; set; }
        public string title { get; set; }
        public string auther { get; set; }
        public long subcatogory_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual sub_catrogoris sub_catrogoris { get; set; }
    }
}
