//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catogory
    {
        public long catogory_id { get; set; }
        public string name { get; set; }
    
        public virtual sub_catrogoris sub_catrogoris { get; set; }
    }
}
