//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class booksEntities2 : DbContext
    {
        public booksEntities2()
            : base("name=booksEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<catogory> catogories { get; set; }
        public virtual DbSet<sub_catrogoris> sub_catrogoris { get; set; }
    
        public virtual ObjectResult<subs_Result> subs(Nullable<int> maincatogory)
        {
            var maincatogoryParameter = maincatogory.HasValue ?
                new ObjectParameter("maincatogory", maincatogory) :
                new ObjectParameter("maincatogory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<subs_Result>("subs", maincatogoryParameter);
        }
    
        public virtual ObjectResult<sub_catrogoris> subssp(Nullable<int> maincatogory)
        {
            var maincatogoryParameter = maincatogory.HasValue ?
                new ObjectParameter("maincatogory", maincatogory) :
                new ObjectParameter("maincatogory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sub_catrogoris>("subssp", maincatogoryParameter);
        }
    
        public virtual ObjectResult<sub_catrogoris> subssp(Nullable<int> maincatogory, MergeOption mergeOption)
        {
            var maincatogoryParameter = maincatogory.HasValue ?
                new ObjectParameter("maincatogory", maincatogory) :
                new ObjectParameter("maincatogory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sub_catrogoris>("subssp", mergeOption, maincatogoryParameter);
        }
    }
}
