//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_catrogoris
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sub_catrogoris()
        {
            this.books = new HashSet<book>();
        }
    
        public long subCatogory_id { get; set; }
        public string name { get; set; }
        public Nullable<long> main_category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book> books { get; set; }
        public virtual catogory catogory { get; set; }
    }
}
